TASK - 1

Create a Python program that converts between different units of measurement.

In [ ]:
def length_conversion(value, unitfrom, unitto):
    if unitfrom == 'm' and unitto == 'ft':
       return value * 3.28084
    elif unitfrom == 'ft' and unitto == 'm':
       return value / 3.28084
    else:
       return None

def weight_conversion(value, unitfrom, unitto):
    if unitfrom == 'kg' and unitto == 'lb':
       return value * 2.20462
    elif unitfrom == 'lb' and unitto == 'kg':
       return value / 2.20462
    else:
       return None

def volume_conversion(value, unitfrom, unitto):
    if unitfrom == 'l' and unitto == 'gal':
       return value * 0.264172
    elif unitfrom == 'gal' and unitto == 'l':
       return value / 0.264172
    else:
       return None

def main():

    print("Select the type of conversion: ")
    print("1. Length (meters to feet)")
    print("2. Weight (kilograms to pounds)")
    print("3. Volume (liters to gallons)")

    try:
        choice = int(input("Enter your choice (1,2,3): "))
        if choice not in [1, 2, 3]:
            print("Invalid!Please select a valid option.")
            return

        value = float(input("Enter the value you want to convert: "))

        if choice == 1:
            print("1. Convert meters to feet")
            print("2. Convert feet to meters")
            length_choice = int(input("Enter your choice (1/2): "))
            unitfrom = "m" if length_choice == 1 else "ft"
            unitto = "ft" if length_choice == 1 else "m"
            result = length_conversion(value, unitfrom, unitto)

        elif choice == 2:
            print("1. Convert kilograms to pounds")
            print("2. Convert pounds to kilograms")
            weight_choice = int(input("Enter your choice (1/2): "))
            unitfrom = "kg" if weight_choice == 1 else "lb"
            unitto = "lb" if weight_choice == 1 else "kg"
            result = weight_conversion(value, unitfrom, unitto)

        elif choice == 3:
            print("1. Convert liters to gallons")
            print("2. Convert gallons to liters")
            volume_choice = int(input("Enter your choice (1/2): "))
            unitfrom = "l" if volume_choice == 1 else "gal"
            unitto = "gal" if volume_choice == 1 else "l"
            result = volume_conversion(value, unitfrom, unitto)

        print(f"Converted Value: {result:.4f}")

    except ValueError:
        print("Invalid input! Please enter a numeric value.")


if __name__ == "__main__":
    main()



Select the type of conversion: 
1. Length (meters to feet)
2. Weight (kilograms to pounds)
3. Volume (liters to gallons)
Enter your choice (1,2,3): 1
Enter the value you want to convert: 12
1. Convert meters to feet
2. Convert feet to meters
Enter your choice (1/2): 1
Converted Value: 39.3701


TASK - 2

Create a Python program that performs various mathematical operations on a list of numbers.

In [ ]:
def sum(numbers):
    """
    Calculate the sum of a list of numbers using a for loop.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: Sum of numbers.
    """
    total = 0
    for num in numbers:
        total += num
    return total

def average(numbers):
    """
    Calculate the average of a list of numbers using a for loop.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: Average value.
    """
    total = 0
    count = 0
    for num in numbers:
        total += num
        count += 1
    return total / count if count > 0 else 0

def maximum(numbers):
    """
    Find the maximum number in a list using a for loop.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: Maximum number.
    """
    max_value = numbers[0]
    for num in numbers:
        if num > max_value:
            max_value = num
    return max_value

def minimum(numbers):
    """
    Find the minimum number in a list using a for loop.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: Minimum number.
    """
    min_value = numbers[0]
    for num in numbers:
        if num < min_value:
            min_value = num
    return min_value

def main():
    """
    Main function to prompt user input and perform calculations.
    """
    print("Math Operations on a List of Numbers")
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = int(input("Enter your choice (1/2/3/4): "))
        if choice not in [1, 2, 3, 4]:
            print("Invalid choice! Please select a valid option.")
            return

        numbers = input("Enter numbers separated by spaces: ").split()
        numbers = [float(num) for num in numbers]

        if not numbers:
            print("Error: No numbers provided.")
            return

        if choice == 1:
            result = sum(numbers)
            operation = "Sum"
        elif choice == 2:
            result = average(numbers)
            operation = "Average"
        elif choice == 3:
            result = maximum(numbers)
            operation = "Maximum"
        else:
            result = minimum(numbers)
            operation = "Minimum"

        print(f"{operation} of given numbers: {result:.4f}")

    except ValueError:
        print("Invalid input! Please enter numeric values only.")


if __name__ == "__main__":
    main()


Math Operations on a List of Numbers
Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1/2/3/4): 1
Enter numbers separated by spaces: 1 2
Sum of given numbers: 3.0000


Nested List

In [ ]:
def extract_everyother(list):
  """Extract every other element from a list."""
  new_list = []
  i=0
  while i < len(list):
    new_list.append(list[i])
    i += 2
  return new_list

def sub_list(list, start, end):
  """ Returns a sublist from given list"""
  new_list = []
  i=start
  while i <= end:
    new_list.append(list[i])
    i += 1
  return new_list

def reverse(list):
  """Reverse a list."""
  new_list = []
  i=len(list)-1
  while i >= 0:
    new_list.append(list[i])
    i -= 1
  return new_list

def remove_firstlast_element(list):
  """Remove the first and last elements from a list."""
  new_list = []
  i=1
  while i < len(list)-1:
    new_list.append(list[i])
    i += 1
  return new_list

def get_n_elements(list,n):
  """Get the first n elements from a list."""
  new_list = []
  i=0
  while i < n and i<len(list):
    new_list.append(list[i])
    i += 1
  return new_list

def get_lastn(list,n):
  """Get the last n elements from a list."""
  new_list = []
  i=len(list)-n
  while i < len(list):
    new_list.append(list[i])
    i += 1
  return new_list

def skip_reverse(list):
  """Extracts elements in reverse order, starting from the second-to-last element and skipping one element."""
  new_list = []
  i=len(list)-2
  while i >= 0:
    new_list.append(list[i])
    i -= 2
  return new_list

def getuser_list():
  """Prompt user to enter number of elements and list elements."""
  while True:
    try:
        n=int(input("Enter number of elements in the list: "))
        if n<= 0:
          print("Enter positive integer.")
          continue
        break
    except ValueError:
        print("Invalid input! Please enter a valid integer.")

  user_list = []
  print(f"Enter {n} elements one by one:")
  for i in range(n):
    while True:
      try:
        num = int(input(f"Enter element {i + 1}: "))
        user_list.append(num)
        break
      except ValueError:
        print("Invalid input! Please enter a number.")
  return user_list

if __name__ == "__main__":
    user_list = getuser_list()

    print("\nOperations on the list:")
    print("Every other element:", extract_everyother(user_list))

    while True:
        try:
            start = int(input("\nEnter start index for sublist: "))
            end = int(input("Enter end index for sublist: "))
            if 0 <= start <= end < len(user_list):
                break
            else:
                print("Invalid range! Start should be <= end and within list size.")
        except ValueError:
            print("Invalid input! Please enter numbers.")

    print("Sublist:", sub_list(user_list, start, end))
    print("Reversed list:", reverse(user_list))
    print("Without first & last:", remove_firstlast_element(user_list))

    while True:
        try:
            n = int(input("\nEnter number of elements to extract from the start: "))
            if n > 0:
                break
            else:
                print("Please enter a positive integer.")
        except ValueError:
            print("Invalid input! Please enter a valid integer.")

    print("First", n, "elements:", get_n_elements(user_list, n))

    while True:
        try:
            n = int(input("\nEnter number of elements to extract from the end: "))
            if n > 0:
                break
            else:
                print("Please enter a positive integer.")
        except ValueError:
            print("Invalid input! Please enter a valid integer.")

    print("Last", n, "elements:", get_lastn(user_list, n))
    print("Reverse skipping:", skip_reverse(user_list))



Enter number of elements in the list: 5
Enter 5 elements one by one:
Enter element 1: 3
Enter element 2: 2
Enter element 3: 5
Enter element 4: 6
Enter element 5: 1

Operations on the list:
Every other element: [3, 5, 1]

Enter start index for sublist: 4
Enter end index for sublist: 6
Invalid range! Start should be <= end and within list size.

Enter start index for sublist: 0
Enter end index for sublist: 4
Sublist: [3, 2, 5, 6, 1]
Reversed list: [1, 6, 5, 2, 3]
Without first & last: [2, 5, 6]

Enter number of elements to extract from the start: 2
First 2 elements: [3, 2]

Enter number of elements to extract from the end: 2
Last 2 elements: [6, 1]
Reverse skipping: [6, 2]


Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:

In [ ]:
import numpy as np
emptyArray = np.empty((2, 2))
print("Empty Array:\n", emptyArray)

onesArray = np.ones((4, 2))
print("\nOnes Array:\n", onesArray)

fillArray = np.full((3, 3), 7)
print("\nArray filled with 7:\n", fillArray)

sampleArray = np.array([[1, 2, 3], [4, 5, 6]])
zeroslike_array = np.zeros_like(sampleArray)
print("\nArray of Zeros as sample array:\n", zeroslike_array)

oneslike_array = np.ones_like(sampleArray)
print("\nArray of Ones as sample array:\n", oneslike_array)

new_list = [1, 2, 3, 4]
numpyArray = np.array(new_list)
print("\nConverted List to NumPy Array:\n", numpyArray)



Empty Array:
 [[5.30761057e-316 0.00000000e+000]
 [0.00000000e+000 9.88131292e-324]]

Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Array of Zeros as sample array:
 [[0 0 0]
 [0 0 0]]

Array of Ones as sample array:
 [[1 1 1]
 [1 1 1]]

Converted List to NumPy Array:
 [1 2 3 4]


Problem - 2: Array Manipulation:

 Numerical Ranges and Array indexing

In [ ]:
arr10_to49 = np.arange(10, 50)
print("Array from 10 to 49:\n", arr10_to49)

matrix0_to8 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix from 0 to 8:\n", matrix0_to8)

identityMatrix = np.eye(3)
print("\nIdentity Matrix:\n", identityMatrix)

randomArray = np.random.random(30)
meanValue = np.mean(randomArray)
print("\nMean of Random Array:\n", meanValue)

randomMatrix = np.random.random((10, 10))
minValue = np.min(randomMatrix)
maxValue = np.max(randomMatrix)
print("\nRandom Matrix Min & Max:\n", minValue, maxValue)

zeroArray = np.zeros(10)
zeroArray[4] = 1
print("\nZero Array with 5th element replaced by 1:\n", zeroArray)

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed Array:\n", reversed_arr)

border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on Border and 0 Inside:\n", border_array)

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\nCheckerboard Pattern:\n", checkerboard)

Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Mean of Random Array:
 0.6252436967631159

Random Matrix Min & Max:
 0.01196879333255696 0.9918544153029187

Zero Array with 5th element replaced by 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed Array:
 [0 4 0 0 2 1]

2D Array with 1 on Border and 0 Inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

addition = x + y
print("Addition of x & y:\n", addition)

subtraction = x - y
print("\nSubtraction of x & y:\n", subtraction)

multiplication= x * 2
print("\nMultiplication of x by 2:\n", multiplication)

square = x ** 2
print("\nSquare of each element in x:\n", square)

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\nDot product of v & w:\n", dot_vw)
print("\nDot product of x & v:\n", dot_xv)
print("\nDot product of x & y:\n", dot_xy)

concat_xy = np.concatenate((x, y), axis=0)
print("\nConcatenation of x and y along rows:\n", concat_xy)

concat_vw = np.vstack((v, w))
print("\nConcatenation of v and w along columns:\n", concat_vw)

try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\nConcatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("\nError concatenating x and v:", e)

Addition of x & y:
 [[ 6  8]
 [10 13]]

Subtraction of x & y:
 [[-4 -4]
 [-4 -3]]

Multiplication of x by 2:
 [[ 2  4]
 [ 6 10]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot product of v & w:
 219

Dot product of x & v:
 [29 77]

Dot product of x & y:
 [[19 22]
 [50 58]]

Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]

Error concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations

In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inverse = np.linalg.inv(A)
check = np.dot(A, A_inverse)
print("A * A⁻¹ = I:\n", check)

AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nMatrix AB:\n", AB)
print("\nMatrix BA:\n", BA)
if not np.array_equal(AB, BA):
    print("\nAB is NOT equal to BA")

AB_Transpose = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)
print("\n(AB)ᵀ:\n", AB_Transpose)
print("\nBᵀ * Aᵀ:\n", BT_AT)
if np.array_equal(AB_Transpose, BT_AT):
    print("\n(AB)ᵀ is equal to Bᵀ * Aᵀ")

A_Matrix = np.array([[2, -3, 1],
                     [1, -1, 2],
                     [3, 1, -1]])

B_matrix = np.array([-1, -3, 9])

A_inverse = np.linalg.inv(A_Matrix)
solution = np.dot(A_inverse, B_matrix)
print("\nLinear Equations (x, y, z):\n", solution)

A * A⁻¹ = I:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Matrix AB:
 [[23 13]
 [51 29]]

Matrix BA:
 [[36 44]
 [13 16]]

AB is NOT equal to BA

(AB)ᵀ:
 [[23 51]
 [13 29]]

Bᵀ * Aᵀ:
 [[23 51]
 [13 29]]

(AB)ᵀ is equal to Bᵀ * Aᵀ

Linear Equations (x, y, z):
 [ 2.  1. -2.]


Experiment: How Fast is Numpy?

In [ ]:
import time

Size = 1_000_000
matrix_size = 1000

list1 = [i for i in range(Size)]
list2 = [i for i in range(Size)]

Array1 = np.arange(Size)
Array2 = np.arange(Size)

start_time = time.time()
list_addition = [list1[i] + list2[i] for i in range(Size)]
list_addition_time = time.time() - start_time
print(f"Python Lists Addition Time: {list_addition_time:.5f} seconds")

start_time = time.time()
numpy_addition = Array1 + Array2
numpy_addition_time = time.time() - start_time
print(f"NumPy Arrays Addition Time: {numpy_addition_time:.5f} seconds")

start_time = time.time()
list_multiplication = [list1[i] * list2[i] for i in range(Size)]
list_multiplication_time = time.time() - start_time
print(f"\nPython Lists Multiplication Time: {list_multiplication_time:.5f} seconds")

start_time = time.time()
numpy_multiplication = Array1 * Array2
numpy_multiplication_time = time.time() - start_time
print(f"NumPy Arrays Multiplication Time: {numpy_multiplication_time:.5f} seconds")

start_time = time.time()
dot_product = sum(list1[i] * list2[i] for i in range(Size))
list_dot_product_time = time.time() - start_time
print(f"\nPython Lists Dot Product Time: {list_dot_product_time:.5f} seconds")

start_time = time.time()
numpy_dot_product = np.dot(Array1, Array2)
numpy_dot_product_time = time.time() - start_time
print(f"NumPy Arrays Dot Product Time: {numpy_dot_product_time:.5f} seconds")

list_matrix1 = [[j for j in range(matrix_size)] for i in range(matrix_size)]
list_matrix2 = [[j for j in range(matrix_size)] for i in range(matrix_size)]

numpy_matrix1 = np.arange(matrix_size ** 2).reshape(matrix_size, matrix_size)
numpy_matrix2 = np.arange(matrix_size ** 2).reshape(matrix_size, matrix_size)

start_time = time.time()
result_matrix = [[sum(a * b for a, b in zip(row, col)) for col in zip(*list_matrix2)] for row in list_matrix1]
list_matrix_multiplication_time = time.time() - start_time
print(f"\nPython Lists Matrix Multiplication Time: {list_matrix_multiplication_time:.5f} seconds")

start_time = time.time()
numpy_matrix_multiplication = np.dot(numpy_matrix1, numpy_matrix2)
numpy_matrix_multiplication_time = time.time() - start_time
print(f"NumPy Arrays Matrix Multiplication Time: {numpy_matrix_multiplication_time:.5f} seconds")

Python Lists Addition Time: 0.14455 seconds
NumPy Arrays Addition Time: 0.00364 seconds

Python Lists Multiplication Time: 0.08437 seconds
NumPy Arrays Multiplication Time: 0.00671 seconds

Python Lists Dot Product Time: 0.14977 seconds
NumPy Arrays Dot Product Time: 0.00199 seconds

Python Lists Matrix Multiplication Time: 200.96041 seconds
NumPy Arrays Matrix Multiplication Time: 2.45625 seconds
